https://dacon.io/competitions/official/236056/overview/description

In [21]:
# ID : 음악 샘플 고유 ID
# 음악 샘플의 특징 정보
# danceability
# energy
# key
# loudness
# speechiness
# acousticness 
# instrumentalness
# liveness
# valence
# tempo
# duration : 음악 재생 시간(길이) (초)
# genre : 음악 장르 (총 15개 종류)

In [2]:
import pandas as pd

In [3]:
train = pd.read_csv('train.csv')
train

,ID,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,genre
0,TRAIN_00000,0.3341,0.9231,10,0.8540,0.3797,0.0080,0.0002,0.7697,0.7902,0.5391,175,trap
1,TRAIN_00001,0.6344,0.5955,10,0.2826,0.1378,0.0000,0.7137,0.1597,0.4162,0.3043,513,techno
2,TRAIN_00002,0.3983,0.1107,8,0.2459,0.0247,0.7740,0.0000,0.5105,0.4291,0.2324,151,Trap Metal
3,TRAIN_00003,0.3139,0.9702,2,0.9252,0.9590,0.0371,0.3015,0.2539,0.0577,0.5406,246,trap
4,TRAIN_00004,0.0735,0.9452,5,0.7702,0.1397,0.2583,0.0015,0.1774,0.1128,0.3176,229,Dark Trap
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25378,TRAIN_25378,0.8814,0.3398,6,0.4602,0.3825,0.4505,0.0000,0.4222,0.8753,0.4081,88,Underground Rap
25379,TRAIN_25379,0.7505,0.5657,0,0.6682,0.1038,0.1281,0.0000,0.0596,0.9583,0.4273,123,Trap Metal
25380,TRAIN_25380,0.2520,0.7617,8,0.4928,0.0410,0.0003,0.8395,0.0843,0.1372,0.7828,353,dnb
25381,TRAIN_25381,0.6202,0.3455,0,0.6499,0.7960,0.4818,0.0000,0.2007,0.0194,0.9756,120,Dark Trap
25382,TRAIN_25382,0.8963,0.4435,9,0.6595,0.1336,0.4673,0.0000,0.2971,0.3320,0.4069,228,Rap

In [18]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25383 entries, 0 to 25382
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                25383 non-null  object
 1   danceability      25383 non-null  float64
 2   energy            25383 non-null  float64
 3   key               25383 non-null  int64
 4   loudness          25383 non-null  float64
 5   speechiness       25383 non-null  float64
 6   acousticness      25383 non-null  float64
 7   instrumentalness  25383 non-null  float64
 8   liveness          25383 non-null  float64
 9   valence           25383 non-null  float64
 10  tempo             25383 non-null  float64
 11  duration          25383 non-null  int64
 12  genre             25383 non-null  int32
dtypes: float64(9), int32(1), int64(2), object(1)
memory usage: 2.4+ MB

In [7]:
train['genre'].unique()

array(['trap', 'techno', 'Trap Metal', 'Dark Trap', 'Rap',
       'Underground Rap', 'hardstyle', 'RnB', 'trance', 'techhouse',
       'dnb', 'Hiphop', 'Emo', 'psytrance', 'Pop'], dtype=object)

In [8]:
# 라벨 인코딩
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train['genre'] = encoder.fit_transform(train['genre'])

In [9]:
train['genre'].unique()

array([14, 12,  6,  0,  4,  7,  9,  5, 13, 11,  8,  2,  1, 10,  3])

In [11]:
# 셋 분리
x = train.drop(columns='genre')
y = train['genre']

In [14]:
# 셋 분리
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=10)

In [24]:
# id 삭제/기록
x_val_id = x_val['ID']
x_train = x_train.drop(columns='ID')
y_train = y_train.drop(columns='ID')
x_val = x_val.drop(columns='ID')

In [25]:
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((20306, 11), (5077, 11), (20306,), (5077,))

In [33]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train, y_train)
y_val_pred = model.predict(x_val)

In [44]:
y_val_pred = pd.DataFrame(y_val_pred).rename(columns = {0:'genre'})
y_val_pred

      genre
0         1
1         5
2         7
3         6
4         0
...     ...
5072     12
5073     12
5074      4
5075      0
5076     11

[5077 rows x 1 columns]

In [48]:
# 모델 스코어 확인
from sklearn.metrics import f1_score
print('score:' , f1_score(y_val, y_val_pred, average='macro'))

score: 0.6344116039143767

제출용

In [68]:
test = pd.read_csv('test.csv')
test

,ID,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration
0,TEST_00000,0.8861,0.6821,2,0.7241,0.3103,0.1451,0.0000,0.5087,0.8863,0.9648,279
1,TEST_00001,0.8495,0.3883,1,0.4495,0.4661,0.6234,0.0004,0.1347,0.4062,0.9051,151
2,TEST_00002,0.2479,0.7549,3,0.7683,0.3131,0.5718,0.0000,0.1250,0.6357,0.3234,196
3,TEST_00003,0.6344,0.9804,1,0.6599,0.0931,0.0020,0.6016,0.8799,0.8790,0.2946,207
4,TEST_00004,0.6237,0.6926,6,0.6716,0.0269,0.0283,0.0001,0.1580,0.9288,0.3642,196
...,...,...,...,...,...,...,...,...,...,...,...,...
16917,TEST_16917,0.5461,0.8686,1,0.6351,0.0656,0.0010,0.8888,0.0047,0.8250,0.2672,161
16918,TEST_16918,0.8443,0.4194,4,0.5065,0.4315,0.1637,0.0241,0.0749,0.9482,0.9186,289
16919,TEST_16919,0.3373,0.9202,10,0.7272,0.4502,0.0791,0.0001,0.1881,0.0992,0.5953,212
16920,TEST_16920,0.4017,0.9741,9,0.6272,0.0768,0.0001,0.8718,0.6649,0.4463,0.4841,617
16921,TEST_16921,0.7676,0.4037,1,0.7554,0.3214,0.0838,0.0059,0.2745,0.1196,0.5966,116

In [70]:
x_test_id = test['ID']
x_test = test.drop(columns='ID')

In [72]:
# 예측
y_test_pred = model.predict(x_test)

In [73]:
y_test_pred = encoder.inverse_transform(y_test_pred)
y_test_pred = pd.DataFrame(y_test_pred).rename(columns = {0:'genre'})
y_test_pred

                 genre
0               Hiphop
1            Dark Trap
2                  Emo
3            techhouse
4                  Pop
...                ...
16917        techhouse
16918           Hiphop
16919        hardstyle
16920        psytrance
16921  Underground Rap

[16922 rows x 1 columns]

In [74]:
final = pd.concat([x_test_id, y_test_pred],axis=1)
final.to_csv('submission.csv',index=False)
pd.read_csv('submission.csv')

               ID            genre
0      TEST_00000           Hiphop
1      TEST_00001        Dark Trap
2      TEST_00002              Emo
3      TEST_00003        techhouse
4      TEST_00004              Pop
...           ...              ...
16917  TEST_16917        techhouse
16918  TEST_16918           Hiphop
16919  TEST_16919        hardstyle
16920  TEST_16920        psytrance
16921  TEST_16921  Underground Rap

[16922 rows x 2 columns]

In [75]:
sample_submission = pd.read_csv('sample_submission.csv')
sample_submission

               ID genre
0      TEST_00000   Pop
1      TEST_00001   Pop
2      TEST_00002   Pop
3      TEST_00003   Pop
4      TEST_00004   Pop
...           ...   ...
16917  TEST_16917   Pop
16918  TEST_16918   Pop
16919  TEST_16919   Pop
16920  TEST_16920   Pop
16921  TEST_16921   Pop

[16922 rows x 2 columns]